version: '3.9'

volumes:
  dbdata:

services:
#  database:
#    image: library/postgres:12-alpine
#    ports:
#      - "5432:5432"
#    env_file:
#      - database/database.env
#    volumes:
#      - dbdata:/var/lib/postgresql/data

  mysql:
    image: debezium/example-mysql:1.5
    ports:
      - "3306:3306"
    env_file:
      - database/mysql.env

  postgres:
    image: debezium/postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - database/database.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:7.9.1
    command: -url=jdbc:postgresql://postgres:5432/postgres -password=development -connectRetries=60 migrate -user=postgres
    depends_on:
      - postgres
    volumes:
      - ./database/sql:/flyway/sql

#  flyway:
#    image: flyway/flyway:7.9.1
#    command: -url=jdbc:mysql://mysql:3306/lineage -password=mysqlpw -connectRetries=60 migrate -user=mysqluser
#    depends_on:
#      - mysql
#    volumes:
#      - ./database/sql:/flyway/sql




  debezium:
    image: debezium/connect
    depends_on:
      - mysql
      - kafka
      - zookeeper
    env_file:
      - debezium/debezium.env
    ports:
    - "8083:8083"

  zookeeper:
    image: debezium/zookeeper:1.5
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka:1.5
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - kafka/kafka.env