spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lineage
    username: postgres
    password: development
  jpa:
    show-sql: true
logging:
  level:
    info.bowkett: DEBUG